### ISSUE TITLE
Generate Recipe for Conda Package

### ISSUE THREAD

**Issue by Heidar-An** [prefix-dev/rattler-build#1004]
Currently, Rattler Build generates `recipe.yml` for PyPI and Cran packages (https://prefix-dev.github.io/rattler-build/latest/recipe_generation/), there should be a feature to generate recipes for conda packages (i.e., those with a `meta.yaml` file). The conversion would be quite simple since the `recipe.yml` and `meta.yml` files are quite similar. 

Is there a reason why this hasn't been added?

I'd be happy to add this if there's no concern with it being part of rattler-build?

**Comment by Heidar-An** [comment]
Oh, taking a look at the source code, it seems there's a `from_yaml` method for `Recipe`

**Comment by baszalmstra** [comment]
Actually the conversion is very much non-trivial because meta.yaml uses selectors and the formats differ in a lot of places. 

However, there is a project that can do the conversion: https://github.com/conda-incubator/conda-recipe-manager

**Comment by Heidar-An** [comment]
Oh, didn't know about the presence of selectors. Luckily, my meta.yaml files don't have those. Thanks for the link!

**Comment by wolfv** [comment]
You can install it using `pixi global install conda-recipe-manager` :)
