### ISSUE TITLE
v0.19.0 lack generate-recipe subcommand

### ISSUE THREAD

**Issue by TTTPOB** [prefix-dev/rattler-build#1005]
I think this should be related to https://github.com/prefix-dev/rattler-build/pull/996

today I installed `rattler-build` using `pixi global install rattler-build` and found that
![image](https://github.com/user-attachments/assets/d33bcdd1-f0b0-4031-84c8-08e686f6d326)

Edit: 
sorry, when I built from source with `--features recipe-generation` the issue persists, and I've found that `recipe-generation` is a default-on feature, so there should be something to do in the code, not just the build.

will check later

**Comment by TTTPOB** [comment]
found that there is a feature called `recipe-generator` not specified in `Cargo.toml` seems responsible for this subcommand
![image](https://github.com/user-attachments/assets/e4b40715-2aee-4b74-9738-ccf9e30d55b7)

so what is the relationship of `recipe-generator` and `recipe-generation`?
![image](https://github.com/user-attachments/assets/273b2898-a0bc-4724-bde1-3d22f678caf6)

**Comment by baszalmstra** [comment]
Thanks for reporting and fixing!

**Comment by TTTPOB** [comment]
> Thanks for reporting and fixing!

You're welcome
