### ISSUE TITLE
Implement `patchelf` and `install_name_tool` functionality with goblin in Rust

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#102]
This would be very nice, for cross-platform builds.

**Comment by wolfv** [comment]
Another option could be the `object` crate: https://docs.rs/object/latest/object/

**Comment by wolfv** [comment]
cc @matthiasbeyer you might want to check out the `object` crate as well :)

**Comment by wolfv** [comment]
I asked a question on the `object` repo: https://github.com/gimli-rs/object/issues/148#issuecomment-1787180928

**Comment by wolfv** [comment]
Another good reference for `install_name_tool` (MachO) is from Homebrew, written in Ruby: https://github.com/Homebrew/ruby-macho/blob/master/lib/macho/macho_file.rb

**Comment by orhun** [comment]
I think this can be closed now.
