### ISSUE TITLE
Packaging fails with "Large file option has not been set"

### ISSUE THREAD

**Issue by najose** [prefix-dev/rattler-build#1034]
rattler-build fails to package certain recipes if the package size is large.

When running rattler-build on such large packages we run into:

```
 ╰─────────────────── (took 2 minutes)
 × error Error building package: Could not open or create, or write to file
Error:   × Could not open or create, or write to file
  ╰─▶ Large file option has not been set
```

Did some initial investigation into this:

- This error might be coming from the `zip` (zip2) crate here: https://github.com/zip-rs/zip2/blob/6d3945645b7f3805068dd8c50d4fe56a66651069/src/write.rs#L587
- Large file mode option in the zip2 crate: https://docs.rs/zip/2.2.0/zip/write/struct.FileOptions.html#tymethod.large_file
- The file options for compressing the package seems to be set here: https://github.com/conda/rattler/blob/698075bed15189bf044bd7eb69ff1871f20333b7/crates/rattler_package_streaming/src/write.rs#L311-L313, and it does not seem to have logic to optionally set `large_file` mode.

**Comment by najose** [comment]
Thinking about this again, this might not be the right repo for this issue, since this is handled by rattler-package-streaming in conda/rattler repo, but I just filed it here as it affects rattler-build.

**Comment by wolfv** [comment]
Thanks for filing this issue! Do you have a notion of "how large"? We should definitely fix this asap.

**Comment by wolfv** [comment]
OK, it's 4 GB apparently. I'll have a look if we should set this always, or if we should try to figure out the file size beforehand.

**Comment by najose** [comment]
Thanks for the quick fix!

**Comment by najose** [comment]
@wolfv, I wonder if https://github.com/prefix-dev/rattler-build/issues/1147 is somehow related to this bug too.
