### ISSUE TITLE
BUG: cannot handle `__osx>=11.0` on osx-arm64?

### ISSUE THREAD

**Issue by h-vetinari** [prefix-dev/rattler-build#1052]
Not really sure where the right place to raise this issue is, perhaps we also need to do something in smithy or conda-forge CI. However, given that conda-build works for this, I'm starting here.

As another issue from https://github.com/conda-forge/zlib-feedstock/pull/83, osx-arm64 builds are failing with:
```
 │ │ Resolving environment for:
 │ │   Platform: osx-64
 │ │   Channels: 
 │ │    - file:///Users/runner/miniforge3/conda-bld/
 │ │    - conda-forge
 │ │   Specs:
 │ │    - __osx >=11.0
thread 'main' panicked at /Users/runner/miniforge3/conda-bld/rattler-build_1725362068760/work/src/cache.rs:171:22:
called `Result::unwrap()` on an `Err` value: DependencyResolutionError(Cannot solve the request because of: No candidates were found for __osx >=11.0.
)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 │ │
 │ ╰─────────────────── (took 16 seconds)
 │
 ╰─────────────────── (took 17 seconds)
```

The images are macOS-12, so we should be satisfying `__osx>=11.0` easily.

**Comment by wolfv** [comment]
Ah, interesting! If this is executing _on_ osx-64 then this should work (ie. if there is no cross-compilation going on). 

But this is going to be easy to reproduce. Maybe we're missing teh virtual package injection when creating test envs.

Thanks!

**Comment by h-vetinari** [comment]
Sorry, perhaps the issue title was misleading. I'm talking about cross-compilation from osx-64 to osx-arm64, not native compilation.

**Comment by wolfv** [comment]
Is it supposed to run the tests? I think not and I think we need a conda-smithy release to fix it for the rattler-build case.

**Comment by h-vetinari** [comment]
No, it isn't supposed to run the tests (we have no emulation, so it would necessarily fail). However, I'm already using a dev install of smithy, and _something_ doesn't seem to be dealing with `--no-test` correctly

**Comment by hadim** [comment]
I might be seeing the same issue at https://github.com/conda-forge/xformers-feedstock/pull/33#issuecomment-2344995161

**Comment by wolfv** [comment]
I have a PR that would print the virtual packages. Thanks for testing @hadim - it's super helpful 🙏

**Comment by hadim** [comment]
> . Thanks for testing @hadim - it's super helpful 🙏

No problem!

The issue only appears on the cf Azure CI. Do you know an easy way to test a custom rattler-build binary (from your PR) within Azure directly? (without hacking too much, the script files)

**Comment by wolfv** [comment]
Unfortunately no. Will cut a release shortly

**Comment by wolfv** [comment]
This was a vicious bug thanks to Apple - the system `plist` file reports a different version depending on which SDK it's linked against. We've rebuilt all (pixi, rattler-build and py-rattler) against the 11.0 SDK and this issue should be gone now! 

Thanks to @beckermr for digging deeply and @baszalmstra for remembering something about `SYSTEM_VERSION_COMPAT`, and @isuruf for pointing out the solution with linking against the 11.0 SDK.
