### ISSUE TITLE
Package content tests Windows lib issue

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#1072]
On Windows for jolt-physics, I see the following in logs (failing):

 │ │   - Library\include\Jolt\TriangleSplitter\TriangleSplitterMean.h
 │ │   - Library\include\Jolt\TriangleSplitter\TriangleSplitterMorton.h
 │ │   - Library\lib\Jolt.dll
 │ │   - Library\lib\Jolt.lib
 │ │   - Library\lib\cmake\Jolt\JoltConfig-distribution.cmake
 │ │   - Library\lib\cmake\Jolt\JoltConfig.cmake
 │ │   - info/about.json
 │ │   - info\hash_input.json
 │ │   - info/index.json
 │ │   - info/licenses/LICENSE
 │ │   - info/paths.json
 │ │   - info/recipe/recipe-scripts-license.txt
 │ │   - info/recipe/recipe.yaml
 │ │   - info/recipe/rendered_recipe.yaml
 │ │   - info/recipe/variant_config.yaml
 │ │   - info/tests\tests.yaml
 │ │ Creating target folder "D:\\bld\\win-64"
 │ │ Compressing archive...
 │ │ Archive written to "D:\\bld\\win-64\\jolt-physics-5.1.0-hc790b64_0.conda"
 │ │
 │ ╰─────────────────── (took 2 seconds)
 │
 │ ╭─ Running package tests
 │ │
 │ │ ╭─ Package content test
 │ │ │  include: "Jolt/Jolt.h" matched:
 │ │ │   - Library/include/Jolt/Jolt.h
 │ │ │  lib: "Jolt" matched:
 │ │ │   - Library/lib/Jolt.lib
 │ │ │ × error Package content test failed:
 │ │ │ × error -   No match for lib glob: Jolt

I believe thsi shoudl have succeeded as both `Jolt.lib` and `Jolt.dll` are present. Or should the `dll` be in the `bin` folder?

**Comment by h-vetinari** [comment]
> Or should the `dll` be in the `bin` folder?

That's the windows standard (at least in the conda world; mingw looks different).

**Comment by baszalmstra** [comment]
Yeah so the build actually puts them in the wrong directory. Because they are in `lib`.

**Comment by baszalmstra** [comment]
I modified the source to make sure to put the dll in the `bin` folder instead.

**Comment by baszalmstra** [comment]
@wolfv I think we can close this. This was a problem with the recipe, not with rattler build

**Comment by wolfv** [comment]
Awesome! :)
