### ISSUE TITLE
Is it possible to prevent `rattler-build build --recipe-dir .` from building certain receipts on certain platforms?

### ISSUE THREAD

**Issue by SobhanMP** [prefix-dev/rattler-build#1084]
I have a forge with a few packages that are not supported on OSX but some that are, is it possible to disable them on OSX from the recipe file?

I'm sorry if this is already answered, but I couldn't find anything about this in the issues or the docs.

**Comment by wolfv** [comment]
Yes, you can add `skip: ["osx"]` to the `build` section (or any other condition, like `skip: ["osx and foo"]`. Let me know if that works!

**Comment by SobhanMP** [comment]
Sorry to miss it in the docs. Thanks! it works great
