### ISSUE TITLE
Converting conda-forge recipe to rattler-build - missing `c_stdlib` to your variant config file?

### ISSUE THREAD

**Issue by luizirber** [prefix-dev/rattler-build#1109]
Hello!

I tried to convert `sourmash-minimal-feedstock` to rattler-build in
https://github.com/conda-forge/sourmash-minimal-feedstock/pull/64

But got this error (locally too) when trying to run `conda-smithy rerender`:
https://github.com/conda-forge/conda-forge-webservices/actions/runs/11281760262/job/31377731285#step:5:2170
```
Error:   × Parsing: failed to render Jinja expression: undefined value: No stdlib
  │ found for language: c
  │ You should add `c_stdlib` to your variant config file. (in <string>:1)
    ╭─[35:7]
 34 │     - ${{ compiler('c') }}
 35 │     - ${{ stdlib("c") }}
    ·       ─────────┬────────
    ·                ╰─┤ undefined value: No stdlib found for language: c
    ·                  │ You should add `c_stdlib` to your variant config file.
 36 │     - ${{ compiler('cxx') }}
    ╰────
```
shouldn't this be pulled from the conda forge pinnings?

I tried looking into [jolt-physics-feedstock](https://github.com/conda-forge/jolt-physics-feedstock/blob/be2718fdc372f0bd5cb33950751eb7eaf092a591/recipe/recipe.yaml#L50) and it seems to be working there, did I miss any configuration on the PR?

**Comment by wolfv** [comment]
The problem in your case was that the `skip` condition was wrong (`<py310` always evaluated to `true`, but you wanted to use `match(python, "<3.10")`).

**Comment by wolfv** [comment]
Fixed by using the correct syntax! :)
