### ISSUE TITLE
bash preamble does not have shebang

### ISSUE THREAD

**Issue by pbauwens** [prefix-dev/rattler-build#1131]
Is it possible to prefix the bash preamble with a #!/bin/bash

Scripts without a shebang are being blocked by the endpoint security software on our workstations which renders rattler-build unusable for us.

**Comment by wolfv** [comment]
Sure thing. Do you want to send a PR?

**Comment by wolfv** [comment]
https://github.com/prefix-dev/rattler-build/blob/91e0b073a321d1c1e3c33ecaec324c7c94296fbd/src/script.rs#L31

**Comment by wolfv** [comment]
fixed by #1132
