### ISSUE TITLE
git relative source path ignores --recipe-dir and --recipe arguments to rattler-build build

### ISSUE THREAD

**Issue by gabuzi** [prefix-dev/rattler-build#1139]
In my brief tests trying to migrate from conda build to rattler-build (v 0.28.0 on OS X), I discovered that this path seems to be relative to the dir of where the `rattler-build build` cmd is issued. I.e., it seems to ignore any `--recipe-dir` argument. This makes any relative git URLs not relative to the recipe dir, contrary to what the docs state. The same is true fore the `--recipe` argument.

I have a `recipe.yaml` two levels deep from the git root and use
```yaml
source:
  git: ../../
```
This works fine if I run `rattler-build build` in the directory of the recipe.

If I run this in the git root with `rattler-build build --recipe-dir level1/level2/` or `rattler-build build --recipe level1/level2/recipe.yaml`, the clone fails. I can clearly see from the computed source directory that it is computed relative to the current directory of the command, so it's no surprise that if I adjust the git source path accoringly, it works.

According to the docs, the path should always be interpreted relative to the recipe dir, regardless of where `rattler-build` is run from.

**Comment by wolfv** [comment]
Thanks. I think the path should be relative to the recipe, indeed. Will have a look asap.

**Comment by wolfv** [comment]
If you want to and a PR in the meantime, that's always appreciated :)
