### ISSUE TITLE
Support for `RATTLER_CACHE_DIR`

### ISSUE THREAD

**Issue by hadim** [prefix-dev/rattler-build#1171]
It would be nice for rattler-build to support `RATTLER_CACHE_DIR` or `RATTLER_BUILD_CACHE_DIR` so we can use a more specific variable than `XDG_CACHE_HOME`.

See https://github.com/conda-forge/conda-smithy/pull/2124#issuecomment-2463119427 for more context.

**Comment by hadim** [comment]
I pushed a PR into rattler at https://github.com/conda/rattler/pull/934.

**Comment by hadim** [comment]
https://github.com/conda/rattler/pull/934 has been merged. It means we can close here once rattler has released a new version, and it has been bumped in rattler-build.

**Comment by wolfv** [comment]
Will try to get a rattler release out tomorrow and a release of rattler-build shortly thereafter! Thanks for working on all this!
