### ISSUE TITLE
Packaging excludes .pyc files if there is no corresponding .py file

### ISSUE THREAD

**Issue by mwiebe** [prefix-dev/rattler-build#1191]
We've got a case where we are building packages that incorporate third party .pyc files that are not shipped with the .py files they came from. Rattler-build is excluding these files from the package due to the code in https://github.com/prefix-dev/rattler-build/blob/31a1e44929f006ca2e777e859240db2bb2579127/src/packaging/file_mapper.rs#L17

```rs
/// We check that each `pyc` file in the package is also present as a `py` file.
/// This is a temporary measure to avoid packaging `pyc` files that are not
/// generated by the build process.
pub fn filter_pyc(path: &Path, new_files: &HashSet<PathBuf>) -> bool {
...
```

In this case the .pyc files that lack their .py file are intentional, so we do not want them excluded. Is it reasonable to switch this logic?

For a workaround, we've implemented our recipes to rename all .pyc files to .pyc2, something like:

```bash
for PYC in "$PREFIX/.../*.pyc; do
    mv "$PYC" "${PYC}2"
done
```

and then in an environment activation script, rename those back to .pyc:

```bash
if [ -f \$CONDA_PREFIX/.../known_module.pyc2 ]; then
    for PYC2 in "\$CONDA_PREFIX/.../*.pyc2; do
        mv "\$PYC2" "\${PYC2%2}"
    done
fi
```

**Comment by wolfv** [comment]
Fixed in #1246 and added a test. Going to be released tomorrow if things go right! :)
