### ISSUE TITLE
Latest rattler-build v0.30.0-h49672d7_1 on windows seems to be broken

### ISSUE THREAD

**Issue by Krande** [prefix-dev/rattler-build#1199]
Hey,

I just tried to install rattler-build v0.30 on windows but there was no rattler-build binaries. I checked the 
([win-64/rattler-build-0.30.0-h49672d7_1.conda](https://anaconda.org/conda-forge/rattler-build/0.30.0/download/win-64/rattler-build-0.30.0-h49672d7_1.conda)) and it seems like the .conda file is empty (only info is present).

![Image](https://github.com/user-attachments/assets/61e8168c-5ee6-4b46-b980-494eca25d97f)

![Image](https://github.com/user-attachments/assets/d17c4a87-fd4b-4297-83f1-bf2704111ac1)

Best Regards
Kristoffer

**Comment by wolfv** [comment]
Ouch! We should move it to broken asap!

**Comment by wolfv** [comment]
PR was merged. Thanks @Krande. The build didn't contain anything specific to windows, so it doesn't really matter anyways.
