### ISSUE TITLE
Timeout during build environment resolution and packages download

### ISSUE THREAD

**Issue by bubaimondalsch** [prefix-dev/rattler-build#1236]
## Problem
While resolving and downloading build environment dependencies, we are constantly hitting the timeout of 5 minutes as some of the packages we have in our hosted Quetz server are quite big.

---
### Request

I notice that this has been fixed on Pixi a while ago (https://github.com/prefix-dev/pixi/pull/1329) and it would be nice to have this in rattler-build as well.

**Comment by wolfv** [comment]
If you send a PR I'll merge it immediately! :)

**Comment by SaulAverageman** [comment]
Sure, https://github.com/prefix-dev/rattler-build/pull/1239 .
