### ISSUE TITLE
`rattler-build upload artifactory` should support Bearer Auth instead of HTTP Basic Auth

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#1254]
`rattler-build upload artifactory` currently only takes `ARTIFACTORY_USER` and `ARTIFACTORY_PASSWORD`. I think it would be nicer to have `ARTIFACTORY_TOKEN` and pass it as a bearer token instead of using HTTP basic auth.

**Comment by wolfv** [comment]
Does Artifactory support this though? Are there any docs that you could link to?

**Comment by pavelzw** [comment]
https://jfrog.com/help/r/jfrog-platform-administration-documentation/access-tokens
