### ISSUE TITLE
Error parsing match specs that contain version and build string combined via `=`

### ISSUE THREAD

**Issue by mgorny** [prefix-dev/rattler-build#1265]
Originally hit this with [libabseil run_exports](https://github.com/conda-forge/abseil-cpp-feedstock/issues/84), but also when converting [triton-feedstock](https://github.com/conda-forge/triton-feedstock/). In https://github.com/conda-forge/abseil-cpp-feedstock/pull/85#pullrequestreview-2503496679, @h-vetinari suggested that this is a bug in rattler-build, so reporting it.

```
Error: 
  × Parsing: failed to parse match spec: the build string '=cuda*' is not valid, it can only contain alphanumeric characters and
  │ underscores
    ╭─[67:7]
 66 │     - filelock
 67 │     - pytorch =*=cuda*
    ·       ────────┬───────
    ·               ╰── error parsing `pytorch =*=cuda*` as a match spec
 68 │     - lit
    ╰────
```

It seems that the only version that works here is:

```yaml
    - pytorch * cuda*
```

**Comment by wolfv** [comment]
Fixed in #1271

**Comment by mgorny** [comment]
Thanks!

**Comment by mgorny** [comment]
Hmm, I think something went wrong here. With 0.33.0, I'm getting:

```
+ rattler-build build --recipe /home/conda/recipe_root -m /home/conda/feedstock_root/.ci_support/linux_64_python3.12.____cpython.yaml --target-platform linux-64 --extra-meta flow_run_id= --extra-meta remote_url= --extra-meta sha=
Error: 
  × Failed to parse recipe

Error: 
  × Parsing: failed to parse match spec: the build string '=cuda*' is not valid, it can only contain alphanumeric characters and
  │ underscores
    ╭─[70:7]
 69 │     - filelock
 70 │     - pytorch =*=cuda*
    ·       ────────┬───────
    ·               ╰── error parsing `pytorch =*=cuda*` as a match spec
 71 │     - lit
    ╰────
```

**Comment by mgorny** [comment]
Ah, okay. @h-vetinari won't like that, I guess.

**Comment by wolfv** [comment]
Just tested and `pytorch [...]` as proposed works like a charm :)

**Comment by h-vetinari** [comment]
> Ah, okay. [@h-vetinari](https://github.com/h-vetinari) won't like that, I guess.

Correct :)

> We don't allow this syntax in the _input_. We allow it when it comes from other packages / repodata though.

Why? 🤔

> Or you can try `pytorch [version="*", build="cuda*"]`

It would probably take some getting used to, but I could live with that, as long as the generated artefacts are compatible with other installers
