### ISSUE TITLE
Is `{{ name[0] }}` not supported?

### ISSUE THREAD

**Issue by beenje** [prefix-dev/rattler-build#149]
I tried modifying the rich recipe from the example to use:

```diff
@@ -1,12 +1,13 @@
 context:
+  name: "rich"
   version: "13.3.3"

 package:
-  name: rich
+  name: "{{ name|lower }}"
   version: "{{ version }}"

 source:
-  - url: https://pypi.io/packages/source/r/rich/rich-{{ version }}.tar.gz
+  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rich-{{ version }}.tar.gz
     sha256: dc84400a9d842b3a9c5ff74addd8eb798d155f36c1c91303888e0a66850d2a15
```

Running `rattler-build` fails:

```
rattler-build build --recipe-file /build/recipe.yaml.new
 INFO rattler_build: Starting the build process
Found variants:
╭─────────────────┬─────────╮
│ Variant         ┆ Version │
╞═════════════════╪═════════╡
│ target_platform ┆ noarch  │
╰─────────────────┴─────────╯

 INFO rattler_build::source: Fetching source from URL: https://pypi.io/packages/source//rich/rich-13.3.3.tar.gz
ERROR rattler_build::source: SHA256 values of downloaded file not matching!
Downloaded = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, should be dc84400a9d842b3a9c5ff74addd8eb798d155f36c1c91303888e0a66850d2a15
ERROR rattler_build::source: Checksum validation failed!
Error: Download could not be validated with checksum!
```

We can see it's trying to download https://pypi.io/packages/source//rich/rich-13.3.3.tar.gz instead of https://pypi.io/packages/source/r/rich/rich-13.3.3.tar.gz

`{{ name[0] }}` is converted to an empty string instead of `r`. Is that expected?

`grayskull` is generating recipes with this URL, so it would be nice if it was working.
Similar URL is shown in the docs: https://prefix-dev.github.io/rattler-build/recipe_file.html#examples

**Comment by wolfv** [comment]
Thanks for the issue @beenje! We're using `minijinja` under the hood and I thought this would work. Let me give it a try locally.

**Comment by wolfv** [comment]
So I just tested with the latest development version and it seems to work (running `cargo run -- build --recipe ./examples/rich/recipe.yaml --render-only`).

We're planning to cut a release today, so maybe you can try again in a couple hours with the latest release :)

**Comment by wolfv** [comment]
OK, new release is out! It should land on conda-forge in ~30 minutes or so :)

**Comment by beenje** [comment]
Same issue with version 0.2.0 I downloaded from the release page:

```
(base) mambauser@35a2f709ff75:~$ ./rattler-build -V
rattler-build 0.2.0
(base) mambauser@35a2f709ff75:~$ ./rattler-build build
 INFO rattler_build: Starting the build process
Found variants:
╭─────────────────┬─────────╮
│ Variant         ┆ Version │
╞═════════════════╪═════════╡
│ target_platform ┆ noarch  │
╰─────────────────┴─────────╯

 INFO rattler_build::source: Fetching source from URL: https://pypi.io/packages/source//rich/rich-13.3.3.tar.gz
```

**Comment by wolfv** [comment]
I opened a PR on minijinja. If we're lucky we get it in in time for the 1.0 release :)

**Comment by wolfv** [comment]
PS: another workaround is to use `{{ name | first }}`
