### ISSUE TITLE
add links to docs in side bar

### ISSUE THREAD

**Issue by raybellwaves** [prefix-dev/rattler-build#159]
Firstly, thanks for this project! I'm excited to try it!

There should be a setting in github to allow you to add a link to the docs ([book here](https://prefix-dev.github.io/rattler-build))

<img width="398" alt="Screen Shot 2023-07-06 at 8 17 14 AM" src="https://github.com/prefix-dev/rattler-build/assets/17162724/48e6c248-92e1-4713-b0a7-04e19bbc6bf3">

**Comment by ruben-arts** [comment]
Thanks for the tip!, I added the link. Have fun testing `rattler-build`!
