### ISSUE TITLE
Write out only unique dependencies

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#211]
Currently it can happen that we store the (exact) same MatchSpec more than once (e.g. once from run_exports, and the other time from the recipe). 
This actually happens in the `toml` test (we end up with `python` 2x in the run dependencies in `index.json`).

We should filter for unique matchspecs before writing the metadata.

**Comment by hadim** [comment]
I gave it a try at https://github.com/prefix-dev/rattler-build/pull/441
