### ISSUE TITLE
Inline if's for requirements

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#213]
It would be nice if we can use inline `if` statements from `minijinja` in the requirements.

E.g.

```
host:
  - ${{ "pkg-config" if osx }}
```

If `osx` is true, this works fine already. If `osx` is false, the parser complains. We need to filter `Yaml::Null` values.

**Comment by wolfv** [comment]
I think our own YAML parser doesn't currenly know about the Yaml::Null node.

**Comment by GrayJack** [comment]
> I think our own YAML parser doesn't currenly know about the Yaml::Null node.

That is correct. I do have a [branch in my fork](https://github.com/GrayJack/rattler-build/tree/rendering-new-approach) that added the Null node, still wip though.
