### ISSUE TITLE
Improve noarch pre-pre-parsing

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#226]
We currently have some custom logic that only attempts to extract the `noarch` setting from the recipe. It doesn't produce fancy `miette` errors and parsing can fail with a slightly cryptic error. 

It would be nice to improve this and use the same parser as is used later for the recipe.

**Comment by matthiasbeyer** [comment]
Can you point me to the things you want to improve, so I can have a look?

**Comment by wolfv** [comment]
Hey, so basically when you have a wrong noarch (like noarch: bliblub in the build section) the parser currently uses "serde" because at the beginning of the program it tries to figure out wether the recipe is noarch or not. 

I think though that @GrayJack has started to work on parsing multiple outputs which also changes how we need to do this and where and so it might not be worth it to try to improve it before the multi-output is done.

**Comment by wolfv** [comment]
This is not relevant anymore. I also just slightly imrpoved the error for wrong noarch fields #571
