### ISSUE TITLE
Extra keys in URL source (and possibly git / path) are ignored

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#229]
We are currently ignoring extra keys in URL Source and possibly the other source types. I think we should raise an error when we encounter unknown keys.

**Comment by JeanChristopheMorinPerso** [comment]
>I think we should raise an error when we encounter unknown keys.

This would be great, and not just for the `source` section! I often see typos in key names when using conda-build and it's always painful to debug since conda-build just ignores key it doesn't know about. `rattler-build` seems to behave the same from what I see (at least in 0.4.0).

**Comment by wolfv** [comment]
The main branch is already better in this regard - but needs some improvement for some sections :)
