### ISSUE TITLE
Support float in variant config?

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [prefix-dev/rattler-build#232]
I was trying rattler-build 0.4.0 and tried to pass Anaconda's conda-build_config to `--variant-config`. I get this error:

```
Starting the build process
No target platform specified, using current platform
2023-10-20T18:37:25.547064Z ERROR rattler_build: Error: Could not parse variant config file (conda_build_config.yaml): OneOrMany could not deserialize any variant:
  One: invalid type: sequence, expected a string
  Many: invalid type: floating point `10.9`, expected a string
```

Since it is very common in YAML to store versions like `10.9` as float, should rattler build automatically convert the float to a string?

If this adds too much complexity, I'm find with changing our cbc file to use explicit strings instead.

**Comment by wolfv** [comment]
Yeah I think I prefer the right type and be strict about it

**Comment by JeanChristopheMorinPerso** [comment]
Perfect, thanks!
