### ISSUE TITLE
implement stdlib Jinja function

### ISSUE THREAD

**Issue by h-vetinari** [prefix-dev/rattler-build#239]
The next release of conda-build is going to [contain](https://github.com/conda/conda-build/issues/4981) a new function to allow expressing constraints on the c standard library version (and implementation).

We plan to use this extensively in conda-forge, because it is the key to handle packages that require newer glibc or Macos versions than our global baseline (in fact, we cannot properly [move](https://github.com/conda-forge/conda-forge.github.io/issues/1844) our baseline on Macos unless we have this).

Given that rattler-build is shaping up to be the next-generation build-tool for conda packages, we'll likely need the same kind of functionality in this tool eventually. I had briefly talked about this with @wolfv, and the implementation shouldn't be hard. It definitely wasn't a big deal on the conda-build [side](https://github.com/conda/conda-build/pull/4999) (most of that PR is docs and tests).

Xref also https://github.com/mamba-org/boa/issues/379

PS. My understanding is that even with https://github.com/conda-incubator/ceps/pull/54, there's still jinja functions under the hood, it would just need to have an extra dollar-sign compared to conda-build/boa, i.e. `${{ stdlib("c") }}`

**Comment by swarnimarun** [comment]
This is now considered blocked on,
https://github.com/conda/conda-build/issues/5053

**Comment by h-vetinari** [comment]
https://github.com/conda/conda-build/issues/5053 was closed a while ago, and we're soon getting to a point where conda-forge feedstocks will contain `{{ stdlib("c") }}` (the bug @wolfv had pointed out about the hash should now be fixed by https://github.com/conda/conda-build/pull/5195).

JFYI :)

**Comment by wolfv** [comment]
Hey @h-vetinari I do still think that the design of the stdlib function was partially because it's hard to change `conda-build`. 

If you had the opportunity to design this feature free from any implementation constraints, would you still do it this way?

**Comment by h-vetinari** [comment]
> If you had the opportunity to design this feature free from any implementation constraints, would you still do it this way?

I won't pretend that I'll manage to give an unbiased answer, but I actually like the conceptual separation between compiler and stdlib. It's an aspect I didn't grasp for a long time, perhaps in no small part due learning about the subject matter mostly through conda(-forge), where the stdlib-aspect is hidden away behind infrastructure-magic.

In an ideal world, I'd like to be able to treat the standard library as any other host-dependence -- which we unfortunately cannot do, at least for the C stdlib, because conda isn't able to ship that --, but assuming we could successfully fake that, then the environment layering question would be an even stronger argument IMO to also reflect that in the recipe. It would also make it clearer where recipes do not need a stdlib at all (freestanding, or whatever).

I get that this arrives relatively late to the game w.r.t. conda, but I kinda think it's worth the migration pain? Not sure why I would otherwise subject myself to this, haha.

If I understand your argument correctly, then you're fully onboard with the need for the relevant knobs, but would like to just encapsulate in the compiler-intrinsic (or virtual package, or however we may call it)? The APIs I've seen for that just don't appeal to me all that much (especially since the stdlib metapackage name changes from platform to platform, forcing yet more selectors), aside from not having a transition story (due to conda limitations around selectors etc.). I guess that could still be an option for rattler or the new recipe format though?

Overall, I'm not that invested in how the implementation looks exactly, though in case of doubt, I prefer the less magic one. But I also think that - at least for conda-forge in 2024 - we don't have the luxury of postponing this until a hypothetical clean room design including transition story arrives (again, rattler may have more freedom there). AFAICT, this topic was neglected basically since inception of conda-forge and is now starting to bite hard. We really need to fix it ASAP, as in, definitely this year, and some of that work will take months even in the best case scenario.

**Comment by h-vetinari** [comment]
Ah, and cross-referencing your last reply from https://github.com/conda/conda-build/issues/5053, you basically said as much yourself:
> I do think that for the future (ie. rattler-build) we'll have an upcoming CEP to define this feature better.

**Comment by wolfv** [comment]
Done in #892
