### ISSUE TITLE
Support injecting variables from other files through jinja syntax

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#244]
Similar to #138

In conda-build, something like `load_file_data('pyproject.toml').get('project').get('version')` is possible. Would be nice to get something similar here as well.

**Comment by wolfv** [comment]
I think my question here is wether this would be a local file or supposed to come from the source section of the recipe. 

I think it would be feasible if it's a local file / recipe. But if the sources need to be downloaded first to discover these missing variables it would create a dependency within the rendering / execution of the recipe that I wouldn't want.

**Comment by pavelzw** [comment]
For my personal use case (where my sources are local too), a local file would be sufficient.
