### ISSUE TITLE
I don't think it unzips .zip files

### ISSUE THREAD

**Issue by codegod100** [prefix-dev/rattler-build#316]
When I point it at .tar.gz it unzips them into work folder, but with .zip files not so much 🤷

**Comment by swarnimarun** [comment]
Yep iirc we don't implement extract for zip files, will take a look. Seems simple enough to resolve, will drop an update after some looking into it.

**Comment by pavelzw** [comment]
Any progress on this? It currently doesn't even put the unextracted file in the work directory.

**Comment by swarnimarun** [comment]
aah thanks I think forgot about this, opened a PR should be fixed for now.

Also note: @pavelzw we never copy unextracted files to work dir. They always remain in the cache_dir(src_cache in this case). (It's a unified directory separate from work dirs and etc.)
