### ISSUE TITLE
Recipes get very large when output directory is inside of recipe directory

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#349]
When you run `rattler-build build` with the recipe file lying on `$PWD/recipe.yaml`, the package will get very large because the whole `output` directory is copied into the package. `rattler-build` should fail or print a warning instead when it detects that the `output` path is part of the recipe directory.

**Comment by pavelzw** [comment]
Fixed by #351

**Comment by wolfv** [comment]
@jacksonwb yes, that could make sense. Please open another issue :)
