### ISSUE TITLE
rattler-build packages not installable via conda on windows

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#355]
I'm trying to install a rattler-build built package with conda 23.3.1 on Windows and get the following error

```
Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(740): An error occurred while installing package 'my-channel::my-package-0.2.1-py312hf046059_0'.
Rolling back transaction: done

[Errno 2] No such file or directory: 'C:\\Users\\pavel\\miniforge3\\envs\\test-env\\Lib\\site-packages\\my_package\\__init__.py'
()
```

The `__init__.py` is in the correct spot in the package. If I compare the `paths.json` with the `paths.json` of a conda-installable package (built with `boa`), I can see that the paths use `/` instead of `\\`.

with rattler-build

```json
{
  "paths": [
    {
      "_path": "Lib\\site-packages\\my_package\\__init__.py",
      "path_type": "hardlink",
      "sha256": "d76cf2832b9f3b53223f66acbad94a2969a6cde7f38e3fd9481227a16f35df6e",
      "size_in_bytes": 155
    },
```

with boa
```json
{
  "paths": [
    {
      "_path": "Lib/site-packages/my_package-0.0.0.dist-info/INSTALLER",
      "path_type": "hardlink",
      "sha256": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
      "size_in_bytes": 5
    },
```

Installing the package via pixi or micromamba works, only conda and mamba fail to install it.

**Comment by wolfv** [comment]
Bas has just pushed a fix to rattler: https://github.com/mamba-org/rattler/pull/416#event-11058084646

Once we update `rattler` here, this should be fixed.

**Comment by dhirschfeld** [comment]
I'd tend to say this is a bug in `conda` - forward-slashes should always work for paths on Windows so it must be some code e.g. naively comparing string representations.

In any case, I guess it's easier to fix here - conform to `conda`'s expectations.

**Comment by dhirschfeld** [comment]
I guess either - on Windows you can use either forward slashes or backward slashes for paths and the filesystem doesn't complain.

That `conda` appears to require a particular convention could be viewed as a bug (since it's not a constraint imposed by the filesystem), or alternatively an undocumented internal api contract 😆

**Comment by wolfv** [comment]
It is actually a better choice because if you build a `noarch` package on Windows, you want it to look similar on Linux etc. (and install fine on UNIX, too).
