### ISSUE TITLE
Error repodata not found

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#365]
I regularly get this error
![image](https://github.com/prefix-dev/rattler-build/assets/29506042/bc63654f-fe6f-41f8-98b8-885cb3e8c641)
This is because I'm only building `noarch` packages and the `osx-arm64` directory is not created but rattler-build expects it.

Would be nice to not be greeted by this error, maybe create the `osx-arm64` directory with an empty repodata by default?

**Comment by wolfv** [comment]
I think these are gone now, right?

**Comment by pavelzw** [comment]
This issue is still there with rattler-build 0.7.0

**Comment by wolfv** [comment]
Both annoying logs should be fixed once #603 is in :)
