### ISSUE TITLE
Support compression level setting for bz2 and zstd

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#376]
It would be nice to have support for something like `--zstd-compression-level` or `--package-format conda:15`

**Comment by swarnimarun** [comment]
There is already zstd support for writing package but [rattler_conda_types](https://github.com/mamba-org/rattler/blob/a6a5faa283ac2f7ba6fc545fd6dfc256a8c08e31/crates/rattler_conda_types/src/package/archive_type.rs#L8) would need to add a archive type / package format for it. That's it.

Then we just would need to add another build option similar to https://github.com/prefix-dev/rattler-build/blob/4bc012f8e052cb7f77b7363417160eefee581496/src/packaging.rs#L947
and use `rattler_package_streaming::write::write_zst_package`.

Not hard to do just not sure if the change is useful?

cc: @wolfv

**Comment by wolfv** [comment]
Hey @swarnimarun there are only two kinds of conda package: `TarBz2` or `Conda`. The `Conda` type contains an outer `zip` file (that is uncompressed) and two inner `tar.zst` files.

When we set the compression level in https://github.com/wolfv/rattler-build/blob/7b1db2f093630f1e651169601667cf40b0ea5b10/src/packaging.rs#L991-L992 that sets the `zstd` compression level (1-21).

I think it would be nice to support an option for these. I don't know wether it should be part of `package-format` or another CLI arg (like `--compression-level {max, default, min, 0-21}`...).
