### ISSUE TITLE
remove `marked-data` fork

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/rattler-build#377]
https://github.com/prefix-dev/rattler-build/blob/4256a4d7507725692bbad70a9f86ff22cc393512/Cargo.toml#L60C2-L60C2

Integrating this fork upstream and using the official version would be good.

@GrayJack Would you be able to create a PR on the upstream repository?

**Comment by wolfv** [comment]
I think the fork just changes the upstream cargo.toml to not use `=x.x` in the version specifiers of its dependencies.

**Comment by wolfv** [comment]
I opened up a PR here: https://github.com/kinnison/marked-data/pull/2
