### ISSUE TITLE
Write documentation & CEP for all the Jinja functions and variables

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#391]
It would be good to have docs for all Jinja variables and also a CEP.

There are some features that have little documentation in conda-build, like `pin_compatible` and where it takes the `pins` from.

If I understand the code correctly, `pin_compatible` can only work properly in the run requirements (or below), for example. In conda-build `m.is_cross` is true whenever there is a host-section -> some more investigation and related cb-code: #368 

We should fully specify all these functions and make sure that the implementation matches.

**Comment by swarnimarun** [comment]
Should be partially fixed after #477.
