### ISSUE TITLE
support git environment variables

### ISSUE THREAD

**Issue by swarnimarun** [prefix-dev/rattler-build#420]
Docs: [docs/source/user-guide/environment-variables.rst](https://github.com/conda/conda-build/blob/ca9de6013cf7d6909f063247512546d351f7a757/docs/source/user-guide/environment-variables.rst#git-environment-variables)

Useful as shown in #404

**Comment by wolfv** [comment]
I think the main challenge is that we don't know what `git` source to pick, and that there could be multiple git sources defined. 

Furthermore, this adds a "cyclic dependency" to the recipe where we first need to pre-render the recipe to get the sources, download the sources, then re-render the recipe with the `GIT` environment variables.

I don't know yet how to solve this in a nice way ... but would be interested to hear your ideas!

**Comment by swarnimarun** [comment]
> I think the main challenge is that we don't know what git source to pick, and that there could be multiple git sources defined.

I actually thought it was the easiest to solve, we can just add order precedence(in the order they are defined). And override to define which is the primary source.

> Furthermore, this adds a "cyclic dependency" to the recipe where we first need to pre-render the recipe to get the sources, download the sources, then re-render the recipe with the GIT environment variables.

Stuck here, as well. As it needs to be known at parse time currently we can't expose any build time artifacts in the first place.

We should still add the variables so that they can used inside the scripts atleast. But this case specifically seems hard to handle(or something we might not want to support).

Currently considering adding a pre-build command to rattler-build as a setup step to handle this kind of situations...

Will check how other build/packaging systems(other than conda) handle it.

For example, in Conan: you can use a dynamic function for version and source, but source can depend on version hence you end up with a cyclic definition issue. And also issues with reproducibility in certain cases. I would prefer to avoid that here.

**Comment by wolfv** [comment]
This one is also solved with #423, correct?

**Comment by swarnimarun** [comment]
Yep, it's solved as we don't need env variables.
We can avoid them entirely and use context variables instead to pass whatever we need to build scripts.

**Comment by lorenzleutgeb** [comment]
@swarnimarun could you please detail how `GIT_DESCRIBE_TAG`, or the output of `git describe` can be obtained with the functions introduced in #423? From what I understand they run `git ls-remote`, which will not indicate the number of commits ahead of the latest tag.

**Comment by wolfv** [comment]
@lorenzleutgeb maybe you can open a new issue with a reproducer and we can look into how to fix this :)
