### ISSUE TITLE
Implement `upload` command for Anaconda.org

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#440]
Upload works for quetz, artifactory and prefix.dev but not for anaconda.org yet.

I think originally @travishathaway was interested in this.

**Comment by 0xbe7a** [comment]
I also wanted to work on this after New Year's Eve. If we can also upload packages with rattler-build, we could theoretically remove the dependency on mamba / conda and conda-forge-ci-setup from conda-forge and thus save 2 solves on each package build.

**Comment by travishathaway** [comment]
@0xbe7a,

Feel free to pick it up!

**Comment by 0xbe7a** [comment]
See #464
