### ISSUE TITLE
test.commands should probably actually be test.scripts ?

### ISSUE THREAD

**Issue by brad-jones** [prefix-dev/rattler-build#445]
The JSON Schema seems to want, `test.scripts` but rattler-build it's self wants `test.commands`, yet the schema doesn't support that.

![image](https://github.com/prefix-dev/rattler-build/assets/2754772/bfa6dc44-9535-4257-be91-66b83cae2ac5)

![image](https://github.com/prefix-dev/rattler-build/assets/2754772/5b1fd7bc-21bd-46ed-a4b7-2036e0cacede)

**Comment by wolfv** [comment]
Hi @brad-jones thanks for your testing! 

I've fixed up the schema here: https://github.com/prefix-dev/recipe-format/pull/9

Now I believe this is aligned with the CEP & rattler-build.
