### ISSUE TITLE
rattler-build sometimes does recursive copies when using `path: ../`

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#450]
When using

```yml
source:
  path: ../
```

and `rattler-build build -r conda-recipe/recipe.yaml`

rattler-build _sometimes_ (this is maybe a race condition?) also copies `output/` into the work folder when `output/` is not in `.gitignore`.
`rattler-build` should fail if the output directory is inside of `source.path` and not excluded by `.gitignore`.

Somewhat similar to #349

**Comment by wolfv** [comment]
Hmm, we could also special case this and forcibly exclude the configured `output` folder

**Comment by pavelzw** [comment]
This would introduce special edge cases where you might want to add some non-rattler-build things from the `output` directory into your conda package. I would prefer just failing if it's not in the `.gitignore` :)

**Comment by garymm** [comment]
I can't figure out the exact set of operations to trigger this, but even when setting --output-dir to a directory that is in .gitignore, I still sometimes see this.
Or at least I think I do, because the error message is supremely unhelpful:
```
rattler_build: Error building package: FileSystem error: 'Io error. Look inside err_kind for more details.'
```

Would be nice to at least provide a better error message.

**Comment by wolfv** [comment]
We now always ignore the output dir when copying recipe contents, so I think this should be fixed.

For copying the source, we would _still_ copy the outputs folder, but that can be worked around with gitignore.
