### ISSUE TITLE
SHA256 calculated incorrectly on ubuntu?

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#486]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: '0.0.1'

package:
  name: test-package
  version: ${{ version }}
source:
  - url: https://github.com/microsoft/mssql-jdbc/raw/v12.2.0/LICENSE
    sha256: 96783d7ed4ff39e20c9ae6642ac6de02692ec8909e9910700e3694d68211ee97
    file_name: mssql-jdbc-license.txt

build:
  number: 0
  script:
    - echo "Hello world!"
```

on macos and windows, building this package is fine. But on ubuntu-latest, for some reason it's complaining...

```
Fetching source from URL: https://github.com/microsoft/mssql-jdbc/raw/v12.2.0/LICENSE
2024-01-12T14:50:24.970153Z ERROR rattler_build::source::url_source: SHA256 values of downloaded file not matching!
Downloaded = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, should be 96783d7ed4ff39e20c9ae6642ac6de02692ec8909e9910700e3694d68211ee97
2024-01-12T14:50:24.970171Z ERROR rattler_build::source::url_source: Checksum validation failed!
Error:   × Download could not be validated with checksum!
```

Any idea what's happening here?
Fails with rattler-build 0.7.0
With rattler-build 0.6.* it's working...

**Comment by 0xbe7a** [comment]
Did this issue persist after a rerun? I have observed this before and it looked like rattler-build does not yet handle network failures gracefully and just received a broken response.

**Comment by pavelzw** [comment]
Yes, this is persisted after multiple reruns.

**Comment by wolfv** [comment]
The URL redirects me to `raw.githubuser...` – could that be the issue (that we don't follow 301 redirects)?

Do you think you can write a test?

**Comment by pavelzw** [comment]
> could that be the issue

maybe 😅 but why only on linux?

> Do you think you can write a test?

the problem is that we don't control this url...

**Comment by 0xbe7a** [comment]
It's a missing flush: `validate_checksum` opens the file again and the last bytes have not yet been written to the fd at this point.
