### ISSUE TITLE
`package_contents` tests issues

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#513]
---

![image](https://github.com/prefix-dev/rattler-build/assets/29506042/ddd39079-0ef4-456e-aed6-1ac18152700e)

should be `%PREFIX%\Library\include\libmamba\mamba.hpp`

---

![image](https://github.com/prefix-dev/rattler-build/assets/29506042/c0317d27-f8c8-4556-a73a-d2a0ccc2a859)

should be `include`

---

![image](https://github.com/prefix-dev/rattler-build/assets/29506042/6a93973a-3d08-4af6-9c18-60340c6523c6)

should be `lib`, `bin`, `include`

---

`include` test is currently not working

---

<img width="405" alt="image" src="https://github.com/prefix-dev/rattler-build/assets/29506042/a5aad06c-763b-4eb2-b02c-1966bd33b9e1">

`package-contents` -> `package_contents`

---

![image](https://github.com/prefix-dev/rattler-build/assets/29506042/9ca49832-28fd-421a-ab3c-06327a127e52)

this should be better documented

```
searches for the following files:
  - `$PREFIX/lib/libmamba.so` on Linux
  - `$PREFIX/lib/libmamba.dylib` on macOS
  - `%PREFX%\Library\lib\mamba.dll` and `%PREFIX%\Library\bin\mamba.bin` on Windows
```

There are also other files that are checked (`libmamba.so.*` on linux, ...). we should document this as well here

---

we should also have a way to specify static libraries in `lib`

---

**Comment by wolfv** [comment]
fixed in #548
