### ISSUE TITLE
Implement `down_prioritize_variant` in `build.variant` section

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#522]
Conda-build uses a "hack" to down-prioritize variants of a package. This hack works by using the `track_features` option. Adding any `track_features` makes the conda, mamba and pixi solvers down prioritize that variant.

We have renamed this option, but ultimately it needs to come up with a (random) `track_feature` per negative point in the down-priorization. This feature _only_ affects the metadata that is written in the recipe.

```yaml
    # used to prefer this variant less
    # note: was `track_features`
    down_prioritize_variant: integer (negative, defaults to 0)
```

**Comment by wolfv** [comment]
This is implemented :)

**Comment by pavelzw** [comment]
#584
