### ISSUE TITLE
rattler-build documentation is a bit broken

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#554]
![image](https://github.com/prefix-dev/rattler-build/assets/29506042/8e28fe1e-bd5e-48ce-a3b1-087f18ca81da)

https://prefix-dev.github.io/rattler-build/experimental_features.md returns a 404 even though it is linked in the side bar.
![image](https://github.com/prefix-dev/rattler-build/assets/29506042/e37d15b3-0d8a-4a4e-9677-4b4c29e8533a)

Also, the deployment of #504 doesn't seem to have worked. 
Both https://prefix-dev.github.io/rattler-build/latest and https://prefix-dev.github.io/rattler-build/dev return a 404.

**Comment by wolfv** [comment]
Fixed :)
