### ISSUE TITLE
Add support for `track_features` with good(!!!!!) documentation

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#558]
https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#track-features

An example use case would be nice in the docs

**Comment by wolfv** [comment]
The idea was to use https://github.com/prefix-dev/rattler-build/issues/522 instead. Wdyt?

**Comment by pavelzw** [comment]
That would be even better 👍🏻
