### ISSUE TITLE
"output directory cannot be in the recipe directory." makes for bad defaults

### ISSUE THREAD

**Issue by benmoss** [prefix-dev/rattler-build#576]
With [this recipe](https://gist.github.com/benmoss/dfa5a177745ce0db656e11dfad752a18) in a folder, I run `rattler-build build` and get this error:

```
rattler-build build
Error:   × The output directory cannot be in the recipe directory.
  │ The current output directory is: /Users/bmoss40/workspace/rattler-build-stuff/output
  │ Select a different output directory with the --output-dir option or set the CONDA_BLD_PATH environment variable
```

This seems unintuitive since I didn't tell rattler-build where to put the output directory as far as I know. If the default is to put it in the current directory, why is that invalid?

**Comment by wolfv** [comment]
Yeah, we might want to designate a 'global' folder (like `~/rattler-build`) or so as the default output directory.
Or maybe something derived from `dirs` (like cache directory/rattler-build or so).

You can modify the directory with an environment variable or by explicitly setting `--output-dir=...` or `CONDA_BLD_PATH=...`

**Comment by mickvangelderen** [comment]
> why is that invalid?

I'd like to understand this as well.

**Comment by wolfv** [comment]
The problem is that we are (usually) copying the whole recipe folder into the package (except when you turn that off by using `--no-include-recipe`).

That means there is a recursive inclusion situation happening.

**Comment by mickvangelderen** [comment]
Would it be hard to implement excluding the output directory from the source files by default? Not sure what method you're using to copy the files.

**Comment by wolfv** [comment]
It would not be so hard. But you can also just say `--output-dir=/my/other/folder` and that shoudl resolve the issue (or use hte `CONDA_BLD` env var).

**Comment by mickvangelderen** [comment]
Sure. The reason this issue popped up for me is that I have a project with a layout like this

```
project/
  ...
  rattler-build/
    output/
    recipe.yaml
    .gitignore # ignores /output/
```

I wanted to try and keep all rattler-build things self contained in the `project/rattler-build/` folder. I also wanted to make use of the defaults that rattler-build provides, like the default output directory `output/` and the default recipe name `recipe.yaml`.

What I think I'll do is move the recipe under another directory `project/rattler-build/recipe/...`. However, I don't think it is ever correct to include the output folder in the ouput recursively and it would be nice if `rattler-build` didn't.

Also, it is not clear from the documentation when it is okay to use `--no-include-recipe`. What do I need the recipe to be included for in the first place?

**Comment by wolfv** [comment]
This is finally fixed :) The output dir will now always be ignored when copying recipe contents.
