### ISSUE TITLE
Why is this variant skipped?

### ISSUE THREAD

**Issue by benmoss** [prefix-dev/rattler-build#577]
With this [recipe](https://gist.github.com/benmoss/dfa5a177745ce0db656e11dfad752a18) on my arm64 macbook I get this result:

```
$ rattler-build build --output-dir /tmp
No target platform specified, using current platform
Found variants:

pyyaml-6.0.1-h60d57d3_0
╭─────────────────┬───────────╮
│ Variant         ┆ Version   │
╞═════════════════╪═══════════╡
│ target_platform ┆ osx-arm64 │
╰─────────────────┴───────────╯

Skipping build for variant: {
    "target_platform": "osx-arm64",
}
```

The docs under [Skipping Builds](https://prefix-dev.github.io/rattler-build/latest/recipe_file/#skipping-builds) say
> By default, a build is never skipped.

but it seems like this is somehow being skipped by default, not sure why.

**Comment by wolfv** [comment]
The recipe contains `skip: true` – and that's why it's skipped :)
