### ISSUE TITLE
fix: currently docs are bit off for `0.7.0`

### ISSUE THREAD

**Issue by swarnimarun** [prefix-dev/rattler-build#586]
We have page for `experimental feature` page added to the `0.7.0` deployment, seems to be a bug during initial push (the page itself gives not found). We would need to remove and redeploy it.

**Comment by wolfv** [comment]
Yeah I think the way I did it was flawed in that sense (I checked out the `mkdocs.yaml` from main which contains that entry).

**Comment by wolfv** [comment]
I think these docs are going to be so "old" so soon that it doesn't matter. At some point we might just clean out some old versions and the problem disappears :)
