### ISSUE TITLE
Question about binary size

### ISSUE THREAD

**Issue by adriendelsalle** [prefix-dev/rattler-build#642]
Can't wait to have it to build conda-forge compatible recipes!

Simple question: why the binary is so..large?
Do you internalize/statically link against all libraries?
I saw the musl libc version, instead of using glibc, which can be useful for use in some alpine or other musl based images.

I don't see the need for a build tool to be self sufficient, if the dependencies can be installed easily using conda packages. It's not like a package manager that has to bootstrap an environment.
Thanks!

**Comment by pavelzw** [comment]
The version on conda-forge is built using `glibc` iirc https://github.com/conda-forge/rattler-build-feedstock/blob/main/recipe/meta.yaml

The conda packages there are ~6-10MB (compressed) 

![image](https://github.com/prefix-dev/rattler-build/assets/29506042/6c6bbac0-b14e-41c8-bbd8-c7098c9a3389)

**Comment by wolfv** [comment]
Indeed, the Rust way of doing things is to statically link everything (with it's benefits and challenges).

I do also think that the binaries on Github are too large. I think there are ways to cut down the size that we haven't started doing yet (enabling `lto` for example).

**Comment by adriendelsalle** [comment]
Thanks a lot for your pointers!
I was mainly curious about the design/architecture that lead to this binaries size.
