### ISSUE TITLE
Make sure that `git@github.com:blabla` urls' work in git source

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#672]
The SSH style URLs don't work because we don't parse them correctly. We might have to introduce a third kind of URL (URL, SSH_URL and Path) when parsign a git source.

**Comment by orhun** [comment]
Related discussion:

- https://github.com/servo/rust-url/issues/220
- https://github.com/servo/rust-url/issues/599

We can use a create like [git-url-parse](https://github.com/tjtelan/git-url-parse-rs) for normalizing Git repo URLs. However, it has some issues:

- https://github.com/tjtelan/git-url-parse-rs/issues/52
- https://github.com/tjtelan/git-url-parse-rs/issues/51

Btw `cargo` has the same issue: https://github.com/rust-lang/cargo/issues/1851
