### ISSUE TITLE
Create a TUI for parallel package building and debugging

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#684]
<img width="1284" alt="Screenshot 2024-02-28 at 13 18 28" src="https://github.com/prefix-dev/rattler-build/assets/885054/79d112ec-ca75-4ddf-b856-f36a8c32027e">

**Comment by wolfv** [comment]
The idea is that each package that is to be built (or each output) get's a little section. First we do this as a mockup with `ratatui`. In the next step, we run all outputs linearly, and send the logs to the proper "tab". Then we start building packages in parallel (as much as possible).

For debugging it would be nice if we could retry a build from this interface and similar things, but this can come later.

**Comment by orhun** [comment]
Here is the mockup that I created:

![rec_20240229T140440](https://github.com/prefix-dev/rattler-build/assets/24392180/b04a9061-295a-4857-849c-78b9f5450fab)

What do you think @wolfv? Should I polish the code and create a draft PR to move on with this?

**Comment by orhun** [comment]
Here is my latest update:

![rec_20240312T173842](https://github.com/prefix-dev/rattler-build/assets/24392180/d81e9442-f78f-46c3-9b6d-0af2c2d04544)

All implemented in #692 behind the `tui` feature flag, so you can now run the following command to launch the TUI:

```sh
$ cargo run --features tui -- build -r recipe.yml --tui
```

Next steps:

- [ ] Horizontal scrolling
- [ ] Debugging (via prompt)
  - [ ] Edit the recipe via `$EDITOR` 
- [ ] Support building multiple packages
  - [ ] Better logging
- [ ] Help view (key bindings)
- [ ] Splash screen
- [ ] Update documentation
