### ISSUE TITLE
Make rattler-build build --render-only output more parsing friendly

### ISSUE THREAD

**Issue by nichmor** [prefix-dev/rattler-build#718]
Running `rattler-build build --render-only --recipe recipe -m recipe/variants.yaml > log.txt`
where 
`recipe/variants.yaml` is

```
python:
  - 3.8.* *_cpython
  - 3.9.* *_cpython

python_impl:
  - cpython
  - cpython
numpy:
  - 1.22
  - 1.22
```

outputs two recipes in log.txt which can't be parsed easily using just json.load

My idea is maybe we can extend this part of code:
https://github.com/prefix-dev/rattler-build/blob/main/src/main.rs#L722
so if it knows that we will have a list of outputs it will output recipes as list of jsons instead of just two json so it can be parsed later.

Also we could extend `build` interface, so it could accept something like `--recipe-output`, and each rendered recipe is saved as a separate file that could be later collected.

**Comment by wolfv** [comment]
Yes, good idea! I think we should merge the `tui` first, and then we can start with these refactors
