### ISSUE TITLE
Ability to pipe a recipe file into `rattler-build build` command

### ISSUE THREAD

**Issue by schuylermartin45** [prefix-dev/rattler-build#734]
It would be nice if I could pipe a recipe file to the `rattler-build build` command so I could avoid writing to disk.

For example, using the [recipe conversion tool](https://github.com/conda-incubator/conda-recipe-manager/blob/main/conda_recipe_manager/commands/convert.py) in a CI environment, I could do something like:

```sh
convert meta.yaml | rattler-build build --render-only
```

This might also be useful for other/future recipe generation tools.

**Comment by orhun** [comment]
Took a quick stab at this at #735

You can test it out and tell me what you think! 🐻
