### ISSUE TITLE
Add support for multiple source URLs (mirrors)

### ISSUE THREAD

**Issue by schuylermartin45** [prefix-dev/rattler-build#830]
From examining the `conda-recipe-manager` integration tests, I've discovered that the `source/url` field only supports scalar values and does not support lists/mirrors yet.

```
Error:   × Parsing: expected a scalar value.
    ╭─[40:5]
 39 │       url:
 40 │ ╭─▶     - ${{ cran_mirror }}/src/contrib/highr_${{ version }}.tar.gz
 41 │ ├─▶     - ${{ cran_mirror }}/src/contrib/Archive/highr/highr_${{ version }}.tar.gz
    · ╰──── expected a string value for `url`
 42 │       sha256: ec55bc1ff66390ed66806dc2a7b6c17dbfd089b3d73fe2e369017f8cb4bc347b
    ╰────
```

From CEP-14:
```
# url pointing to the source tar.gz|zip|tar.bz2|... (this can be a list of mirrors that point to the same file)
url: url | [url]
```

**Comment by schuylermartin45** [comment]
Presumably the basename of each member of the list should be identical. I'm not sure if we want to perform that in the validation phase.

**Comment by wolfv** [comment]
Yep! We should implement this. 
I am not sure that the base name needs to be the same. 

For archives, they get extracted automatically.

For other files, one could force it using the `file_name: <>` field.
