### ISSUE TITLE
don't record recipe source extraction folder

### ISSUE THREAD

**Issue by nichmor** [prefix-dev/rattler-build#843]
After build on linux a conda package using rattler-build, it is not possible to rebuild it on macos. 
https://github.com/nichmor/reproducible-builds-rattler-build/actions/runs/9158037615/job/25175659418#step:5:8

I think the problem is that we record where initially we extracted the recipe source, and on rebuild phase we try to recreate that folder - which on a github runner is not possible anymore.

**Comment by wolfv** [comment]
Interesting! We can try to set `export CONDA_BLD_PATH=/opt/rattler-build` (or use `--output-dir` on the command line) to build in a more deterministic location outside the `home` folder.

**Comment by wolfv** [comment]
@nichmor I do think that after our discussion we can close this, right? Since we _do_ need to record these folders for reproducibility reasons.

**Comment by nichmor** [comment]
> @nichmor I do think that after our discussion we can close this, right? Since we _do_ need to record these folders for reproducibility reasons.

yes!
as discussed  for rebuilding we can output to some `common` folder, like /opt instead of /usr/me
