### ISSUE TITLE
curl is not reproducible from macos 13 to macos 12

### ISSUE THREAD

**Issue by nichmor** [prefix-dev/rattler-build#862]
![image](https://github.com/prefix-dev/rattler-build/assets/25200469/2057d984-b68f-455d-a769-81a736fb1f2f)
![Screenshot 2024-05-27 at 18 00 02](https://github.com/prefix-dev/rattler-build/assets/25200469/aa6e470d-66dd-4a61-85fc-3ab5d60b5bf5)

it has different content inside info and pkg-info

**Comment by wolfv** [comment]
I am going to close this for now as there is not much `rattler-build` can do in this case. But we should document these in the reproducible-builds repo :)
