### ISSUE TITLE
Upper bound wrong?

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#954]
@pavelzw pointed out that some upper bound calculation might be slightly off:

- `${{ pin_subpackage('foo', lower_bound="x.x.x", upper_bound="x.x.x") }}`

Apparently results in `>=0.11.1post1+HASH,<1`

Should double check what's going on!

**Comment by pavelzw** [comment]
this is fixed with the latest release. thanks @wolfv
