### ISSUE TITLE
Parse `variants.yaml` per recipe when using `--recipe-dir`

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/rattler-build#974]
Currently, variants can only be selected globally using the `--variant-config` flag. However, sometimes a per-recipe variant configuration file can be quite useful.

I propose that for each recipe found when using `--recipe-dir` we also read a `variants.yaml` file in the same directory to allow per recipe overrides.

**Comment by wolfv** [comment]
Sounds good to me!
